package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/odysseia-greek/makedonia/alexandros/graph/model"
	koinos "github.com/odysseia-greek/makedonia/filippos/gen/go/koinos/v1"
	v1 "github.com/odysseia-greek/makedonia/ptolemaios/gen/go/v1"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.AggregatedHealthResponse, error) {
	return r.Handler.Health(ctx)
}

// CounterTopFive is the resolver for the counterTopFive field.
func (r *queryResolver) CounterTopFive(ctx context.Context) (*model.EukleidesTopFiveResponse, error) {
	return r.Handler.TopFive(ctx)
}

// CounterService is the resolver for the counterService field.
func (r *queryResolver) CounterService(ctx context.Context, name string) (*model.EukleidesTopFive, error) {
	return r.Handler.TopFiveForService(ctx, name)
}

// CounterSession is the resolver for the CounterSession field.
func (r *queryResolver) CounterSession(ctx context.Context, sessionID string) (*model.EukleidesTopFiveResponse, error) {
	return r.Handler.TopFiveForSession(ctx, sessionID)
}

// Text is the resolver for the text field.
func (r *queryResolver) Text(ctx context.Context, input model.ExpandableSearchQueryInput) (*model.ExtendedResponse, error) {
	textResponse, _ := r.Handler.Extended(ctx, &v1.ExtendedSearch{Word: input.Word})

	response := &model.ExtendedResponse{
		FoundInText: textResponse,
	}

	return response, nil
}

// Fuzzy is the resolver for the fuzzy field.
func (r *queryResolver) Fuzzy(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	language := parseLanguage(input.Language)

	request := &koinos.SearchQuery{
		Word:            input.Word,
		Language:        language,
		NumberOfResults: *input.Size,
	}
	return r.Handler.Fuzzy(ctx, request)
}

// Exact is the resolver for the exact field.
func (r *queryResolver) Exact(ctx context.Context, input model.ExpandableSearchQueryInput) (*model.ExtendedResponse, error) {
	language := parseLanguage(input.Language)

	request := &koinos.SearchQuery{
		Word:            input.Word,
		Language:        language,
		NumberOfResults: *input.Size,
	}
	exactResponse, err := r.Handler.Exact(ctx, request)
	if err != nil {
		return nil, err
	}

	var meros []*model.Hit
	var textResponse *model.AnalyzeTextResponse
	if input.Expand {
		fuzzyResponses, _ := r.Handler.Fuzzy(ctx, request)

		for _, fuzzy := range fuzzyResponses.Results {
			// Skip the exact match
			if fuzzy.Headword == input.Word {
				continue
			}

			hit := model.Hit{
				English:    nil,
				Greek:      &fuzzy.Headword,
				LinkedWord: fuzzy.LinkedWord,
				Original:   fuzzy.Normalized,
			}

			for _, gloss := range fuzzy.QuickGlosses {
				if gloss.Language == "en" {
					hit.English = &gloss.Gloss
				}
			}
			meros = append(meros, &hit)
		}

		textResponse, _ = r.Handler.Extended(ctx, &v1.ExtendedSearch{Word: request.Word})
	}

	response := &model.ExtendedResponse{
		Results:      exactResponse.Results,
		PageInfo:     exactResponse.PageInfo,
		SimilarWords: meros,
		FoundInText:  textResponse,
	}

	return response, nil
}

// Phrase is the resolver for the phrase field.
func (r *queryResolver) Phrase(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	language := parseLanguage(input.Language)

	request := &koinos.SearchQuery{
		Word:            input.Word,
		Language:        language,
		NumberOfResults: *input.Size,
	}
	return r.Handler.Phrase(ctx, request)
}

// Partial is the resolver for the partial field.
func (r *queryResolver) Partial(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	language := parseLanguage(input.Language)

	request := &koinos.SearchQuery{
		Word:            input.Word,
		Language:        language,
		NumberOfResults: *input.Size,
	}
	return r.Handler.Partial(ctx, request)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
