package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/odysseia-greek/agora/plato/config"
	"github.com/odysseia-greek/makedonia/alexandros/graph/model"
	koinos "github.com/odysseia-greek/makedonia/filippos/gen/go/koinos/v1"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.AggregatedHealthResponse, error) {
	requestID, _ := ctx.Value(config.HeaderKey).(string)
	sessionId, _ := ctx.Value(config.SessionIdKey).(string)
	return r.Handler.Health(requestID, sessionId)
}

// CounterTopFive is the resolver for the counterTopFive field.
func (r *queryResolver) CounterTopFive(ctx context.Context) (*model.EukleidesTopFiveResponse, error) {
	return r.Handler.TopFive(ctx)
}

// CounterService is the resolver for the counterService field.
func (r *queryResolver) CounterService(ctx context.Context, name string) ([]*model.EukleidesTopFive, error) {
	panic(fmt.Errorf("not implemented: CounterService - counterService"))
}

// CounterSession is the resolver for the CounterSession field.
func (r *queryResolver) CounterSession(ctx context.Context, sessionID string) ([]*model.EukleidesTopFive, error) {
	panic(fmt.Errorf("not implemented: CounterSession - CounterSession"))
}

// Fuzzy is the resolver for the fuzzy field.
func (r *queryResolver) Fuzzy(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	requestID, _ := ctx.Value(config.HeaderKey).(string)
	sessionId, _ := ctx.Value(config.SessionIdKey).(string)

	var language koinos.Language
	switch *input.Language {
	case model.LanguageLangGreek:
		language = koinos.Language_LANG_GREEK
	case model.LanguageLangEnglish:
		language = koinos.Language_LANG_ENGLISH
	case model.LanguageLangDutch:
		language = koinos.Language_LANG_DUTCH
	default:
		language = koinos.Language_LANG_GREEK
	}

	request := &koinos.SearchQuery{
		Word:     input.Word,
		Language: language,
	}
	return r.Handler.Fuzzy(request, requestID, sessionId)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
