FROM golang:1.25.4-alpine AS builder

ARG project_name
ENV project_name=${project_name}

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Install ginkgo CLI for building
RUN go install github.com/onsi/ginkgo/v2/ginkgo

# Build the test binary for the current directory
RUN ginkgo build -o /app/${project_name}.test

FROM alpine:3.23.2 as prod

ARG project_name
ENV project_name=${project_name}

WORKDIR /app
COPY --from=builder /app/${project_name}.test .

# Run with -ginkgo.v for verbose output
ENTRYPOINT [ "/app/dareios.test", "-ginkgo.v" ]