// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/eukleides.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EukleidesClient is the client API for Eukleides service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EukleidesClient interface {
	CreateNewEntry(ctx context.Context, opts ...grpc.CallOption) (Eukleides_CreateNewEntryClient, error)
	RetrieveTopFive(ctx context.Context, in *TopFiveRequest, opts ...grpc.CallOption) (*TopFiveResponse, error)
	RetrieveTopFiveService(ctx context.Context, in *TopFiveServiceRequest, opts ...grpc.CallOption) (*TopFive, error)
	RetrieveTopFiveForSession(ctx context.Context, in *TopFiveSessionRequest, opts ...grpc.CallOption) (*TopFiveResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type eukleidesClient struct {
	cc grpc.ClientConnInterface
}

func NewEukleidesClient(cc grpc.ClientConnInterface) EukleidesClient {
	return &eukleidesClient{cc}
}

func (c *eukleidesClient) CreateNewEntry(ctx context.Context, opts ...grpc.CallOption) (Eukleides_CreateNewEntryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Eukleides_ServiceDesc.Streams[0], "/makedonia_eukleides.Eukleides/CreateNewEntry", opts...)
	if err != nil {
		return nil, err
	}
	x := &eukleidesCreateNewEntryClient{stream}
	return x, nil
}

type Eukleides_CreateNewEntryClient interface {
	Send(*CountCreationRequestSet) error
	CloseAndRecv() (*CountStreamResponse, error)
	grpc.ClientStream
}

type eukleidesCreateNewEntryClient struct {
	grpc.ClientStream
}

func (x *eukleidesCreateNewEntryClient) Send(m *CountCreationRequestSet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eukleidesCreateNewEntryClient) CloseAndRecv() (*CountStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CountStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eukleidesClient) RetrieveTopFive(ctx context.Context, in *TopFiveRequest, opts ...grpc.CallOption) (*TopFiveResponse, error) {
	out := new(TopFiveResponse)
	err := c.cc.Invoke(ctx, "/makedonia_eukleides.Eukleides/RetrieveTopFive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eukleidesClient) RetrieveTopFiveService(ctx context.Context, in *TopFiveServiceRequest, opts ...grpc.CallOption) (*TopFive, error) {
	out := new(TopFive)
	err := c.cc.Invoke(ctx, "/makedonia_eukleides.Eukleides/RetrieveTopFiveService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eukleidesClient) RetrieveTopFiveForSession(ctx context.Context, in *TopFiveSessionRequest, opts ...grpc.CallOption) (*TopFiveResponse, error) {
	out := new(TopFiveResponse)
	err := c.cc.Invoke(ctx, "/makedonia_eukleides.Eukleides/RetrieveTopFiveForSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eukleidesClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/makedonia_eukleides.Eukleides/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EukleidesServer is the server API for Eukleides service.
// All implementations must embed UnimplementedEukleidesServer
// for forward compatibility
type EukleidesServer interface {
	CreateNewEntry(Eukleides_CreateNewEntryServer) error
	RetrieveTopFive(context.Context, *TopFiveRequest) (*TopFiveResponse, error)
	RetrieveTopFiveService(context.Context, *TopFiveServiceRequest) (*TopFive, error)
	RetrieveTopFiveForSession(context.Context, *TopFiveSessionRequest) (*TopFiveResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedEukleidesServer()
}

// UnimplementedEukleidesServer must be embedded to have forward compatible implementations.
type UnimplementedEukleidesServer struct {
}

func (UnimplementedEukleidesServer) CreateNewEntry(Eukleides_CreateNewEntryServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateNewEntry not implemented")
}
func (UnimplementedEukleidesServer) RetrieveTopFive(context.Context, *TopFiveRequest) (*TopFiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTopFive not implemented")
}
func (UnimplementedEukleidesServer) RetrieveTopFiveService(context.Context, *TopFiveServiceRequest) (*TopFive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTopFiveService not implemented")
}
func (UnimplementedEukleidesServer) RetrieveTopFiveForSession(context.Context, *TopFiveSessionRequest) (*TopFiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTopFiveForSession not implemented")
}
func (UnimplementedEukleidesServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEukleidesServer) mustEmbedUnimplementedEukleidesServer() {}

// UnsafeEukleidesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EukleidesServer will
// result in compilation errors.
type UnsafeEukleidesServer interface {
	mustEmbedUnimplementedEukleidesServer()
}

func RegisterEukleidesServer(s grpc.ServiceRegistrar, srv EukleidesServer) {
	s.RegisterService(&Eukleides_ServiceDesc, srv)
}

func _Eukleides_CreateNewEntry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EukleidesServer).CreateNewEntry(&eukleidesCreateNewEntryServer{stream})
}

type Eukleides_CreateNewEntryServer interface {
	SendAndClose(*CountStreamResponse) error
	Recv() (*CountCreationRequestSet, error)
	grpc.ServerStream
}

type eukleidesCreateNewEntryServer struct {
	grpc.ServerStream
}

func (x *eukleidesCreateNewEntryServer) SendAndClose(m *CountStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eukleidesCreateNewEntryServer) Recv() (*CountCreationRequestSet, error) {
	m := new(CountCreationRequestSet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Eukleides_RetrieveTopFive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopFiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EukleidesServer).RetrieveTopFive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/makedonia_eukleides.Eukleides/RetrieveTopFive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EukleidesServer).RetrieveTopFive(ctx, req.(*TopFiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eukleides_RetrieveTopFiveService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopFiveServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EukleidesServer).RetrieveTopFiveService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/makedonia_eukleides.Eukleides/RetrieveTopFiveService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EukleidesServer).RetrieveTopFiveService(ctx, req.(*TopFiveServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eukleides_RetrieveTopFiveForSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopFiveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EukleidesServer).RetrieveTopFiveForSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/makedonia_eukleides.Eukleides/RetrieveTopFiveForSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EukleidesServer).RetrieveTopFiveForSession(ctx, req.(*TopFiveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eukleides_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EukleidesServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/makedonia_eukleides.Eukleides/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EukleidesServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Eukleides_ServiceDesc is the grpc.ServiceDesc for Eukleides service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eukleides_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "makedonia_eukleides.Eukleides",
	HandlerType: (*EukleidesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveTopFive",
			Handler:    _Eukleides_RetrieveTopFive_Handler,
		},
		{
			MethodName: "RetrieveTopFiveService",
			Handler:    _Eukleides_RetrieveTopFiveService_Handler,
		},
		{
			MethodName: "RetrieveTopFiveForSession",
			Handler:    _Eukleides_RetrieveTopFiveForSession_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Eukleides_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateNewEntry",
			Handler:       _Eukleides_CreateNewEntry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/eukleides.proto",
}
