// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/eukleides.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountCreationRequestSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*CountCreationRequest `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *CountCreationRequestSet) Reset() {
	*x = CountCreationRequestSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountCreationRequestSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCreationRequestSet) ProtoMessage() {}

func (x *CountCreationRequestSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCreationRequestSet.ProtoReflect.Descriptor instead.
func (*CountCreationRequestSet) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{0}
}

func (x *CountCreationRequestSet) GetRequest() []*CountCreationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type CountCreationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word        string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	SearchType  string `protobuf:"bytes,3,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	SessionId   string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *CountCreationRequest) Reset() {
	*x = CountCreationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCreationRequest) ProtoMessage() {}

func (x *CountCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCreationRequest.ProtoReflect.Descriptor instead.
func (*CountCreationRequest) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{1}
}

func (x *CountCreationRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *CountCreationRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CountCreationRequest) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

func (x *CountCreationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CountStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack string `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *CountStreamResponse) Reset() {
	*x = CountStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountStreamResponse) ProtoMessage() {}

func (x *CountStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountStreamResponse.ProtoReflect.Descriptor instead.
func (*CountStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{2}
}

func (x *CountStreamResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type TopFiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TopFiveRequest) Reset() {
	*x = TopFiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopFiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFiveRequest) ProtoMessage() {}

func (x *TopFiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFiveRequest.ProtoReflect.Descriptor instead.
func (*TopFiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{3}
}

type TopFiveServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TopFiveServiceRequest) Reset() {
	*x = TopFiveServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopFiveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFiveServiceRequest) ProtoMessage() {}

func (x *TopFiveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFiveServiceRequest.ProtoReflect.Descriptor instead.
func (*TopFiveServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{4}
}

func (x *TopFiveServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TopFiveSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *TopFiveSessionRequest) Reset() {
	*x = TopFiveSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopFiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFiveSessionRequest) ProtoMessage() {}

func (x *TopFiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFiveSessionRequest.ProtoReflect.Descriptor instead.
func (*TopFiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{5}
}

func (x *TopFiveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TopFiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopFive []*TopFive `protobuf:"bytes,1,rep,name=top_five,json=topFive,proto3" json:"top_five,omitempty"`
}

func (x *TopFiveResponse) Reset() {
	*x = TopFiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopFiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFiveResponse) ProtoMessage() {}

func (x *TopFiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFiveResponse.ProtoReflect.Descriptor instead.
func (*TopFiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{6}
}

func (x *TopFiveResponse) GetTopFive() []*TopFive {
	if x != nil {
		return x.TopFive
	}
	return nil
}

type TopFive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Word        string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	LastUsed    string `protobuf:"bytes,3,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	Count       int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp   int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TopFive) Reset() {
	*x = TopFive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopFive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopFive) ProtoMessage() {}

func (x *TopFive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopFive.ProtoReflect.Descriptor instead.
func (*TopFive) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{7}
}

func (x *TopFive) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TopFive) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *TopFive) GetLastUsed() string {
	if x != nil {
		return x.LastUsed
	}
	return ""
}

func (x *TopFive) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopFive) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Health bool `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_eukleides_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eukleides_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_eukleides_proto_rawDescGZIP(), []int{9}
}

var File_proto_eukleides_proto protoreflect.FileDescriptor

var file_proto_eukleides_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e,
	0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x17,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74, 0x12, 0x43, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64,
	0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a,
	0x14, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x13,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x54, 0x6f, 0x70, 0x46, 0x69,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x0f,
	0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x5f, 0x66, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75,
	0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x52,
	0x07, 0x74, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x07, 0x54, 0x6f, 0x70,
	0x46, 0x69, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x28, 0x0a, 0x0e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x81, 0x04, 0x0a, 0x09, 0x45, 0x75, 0x6b, 0x6c,
	0x65, 0x69, 0x64, 0x65, 0x73, 0x12, 0x6a, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2c, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f,
	0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69,
	0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x12, 0x5e, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x54, 0x6f, 0x70,
	0x46, 0x69, 0x76, 0x65, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61,
	0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x46, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x6b, 0x65,
	0x64, 0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e,
	0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x64, 0x0a, 0x16, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x54, 0x6f, 0x70,
	0x46, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x2e, 0x6d, 0x61,
	0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65,
	0x73, 0x2e, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f,
	0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x6f,
	0x70, 0x46, 0x69, 0x76, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61,
	0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x46, 0x69,
	0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b,
	0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x46, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x12, 0x22, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61, 0x5f, 0x65, 0x75, 0x6b,
	0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e, 0x69, 0x61,
	0x5f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x79, 0x73, 0x73, 0x65,
	0x69, 0x61, 0x2d, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x6e,
	0x69, 0x61, 0x2f, 0x65, 0x75, 0x6b, 0x6c, 0x65, 0x69, 0x64, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_eukleides_proto_rawDescOnce sync.Once
	file_proto_eukleides_proto_rawDescData = file_proto_eukleides_proto_rawDesc
)

func file_proto_eukleides_proto_rawDescGZIP() []byte {
	file_proto_eukleides_proto_rawDescOnce.Do(func() {
		file_proto_eukleides_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_eukleides_proto_rawDescData)
	})
	return file_proto_eukleides_proto_rawDescData
}

var file_proto_eukleides_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_eukleides_proto_goTypes = []interface{}{
	(*CountCreationRequestSet)(nil), // 0: makedonia_eukleides.CountCreationRequestSet
	(*CountCreationRequest)(nil),    // 1: makedonia_eukleides.CountCreationRequest
	(*CountStreamResponse)(nil),     // 2: makedonia_eukleides.CountStreamResponse
	(*TopFiveRequest)(nil),          // 3: makedonia_eukleides.TopFiveRequest
	(*TopFiveServiceRequest)(nil),   // 4: makedonia_eukleides.TopFiveServiceRequest
	(*TopFiveSessionRequest)(nil),   // 5: makedonia_eukleides.TopFiveSessionRequest
	(*TopFiveResponse)(nil),         // 6: makedonia_eukleides.TopFiveResponse
	(*TopFive)(nil),                 // 7: makedonia_eukleides.TopFive
	(*HealthResponse)(nil),          // 8: makedonia_eukleides.HealthResponse
	(*HealthRequest)(nil),           // 9: makedonia_eukleides.HealthRequest
}
var file_proto_eukleides_proto_depIdxs = []int32{
	1, // 0: makedonia_eukleides.CountCreationRequestSet.request:type_name -> makedonia_eukleides.CountCreationRequest
	7, // 1: makedonia_eukleides.TopFiveResponse.top_five:type_name -> makedonia_eukleides.TopFive
	0, // 2: makedonia_eukleides.Eukleides.CreateNewEntry:input_type -> makedonia_eukleides.CountCreationRequestSet
	3, // 3: makedonia_eukleides.Eukleides.RetrieveTopFive:input_type -> makedonia_eukleides.TopFiveRequest
	4, // 4: makedonia_eukleides.Eukleides.RetrieveTopFiveService:input_type -> makedonia_eukleides.TopFiveServiceRequest
	5, // 5: makedonia_eukleides.Eukleides.RetrieveTopFiveForSession:input_type -> makedonia_eukleides.TopFiveSessionRequest
	9, // 6: makedonia_eukleides.Eukleides.Health:input_type -> makedonia_eukleides.HealthRequest
	2, // 7: makedonia_eukleides.Eukleides.CreateNewEntry:output_type -> makedonia_eukleides.CountStreamResponse
	6, // 8: makedonia_eukleides.Eukleides.RetrieveTopFive:output_type -> makedonia_eukleides.TopFiveResponse
	7, // 9: makedonia_eukleides.Eukleides.RetrieveTopFiveService:output_type -> makedonia_eukleides.TopFive
	6, // 10: makedonia_eukleides.Eukleides.RetrieveTopFiveForSession:output_type -> makedonia_eukleides.TopFiveResponse
	8, // 11: makedonia_eukleides.Eukleides.Health:output_type -> makedonia_eukleides.HealthResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_eukleides_proto_init() }
func file_proto_eukleides_proto_init() {
	if File_proto_eukleides_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_eukleides_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountCreationRequestSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountCreationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopFiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopFiveServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopFiveSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopFiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopFive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_eukleides_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_eukleides_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eukleides_proto_goTypes,
		DependencyIndexes: file_proto_eukleides_proto_depIdxs,
		MessageInfos:      file_proto_eukleides_proto_msgTypes,
	}.Build()
	File_proto_eukleides_proto = out.File
	file_proto_eukleides_proto_rawDesc = nil
	file_proto_eukleides_proto_goTypes = nil
	file_proto_eukleides_proto_depIdxs = nil
}
