// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggregatedHealthResponse struct {
	Healthy  *bool            `json:"healthy,omitempty"`
	Time     *string          `json:"time,omitempty"`
	Version  *string          `json:"version,omitempty"`
	Services []*ServiceHealth `json:"services,omitempty"`
}

type DatabaseInfo struct {
	Healthy       *bool   `json:"healthy,omitempty"`
	ClusterName   *string `json:"clusterName,omitempty"`
	ServerName    *string `json:"serverName,omitempty"`
	ServerVersion *string `json:"serverVersion,omitempty"`
}

type Query struct {
}

type ServiceHealth struct {
	Name         *string       `json:"name,omitempty"`
	Healthy      *bool         `json:"healthy,omitempty"`
	Version      *string       `json:"version,omitempty"`
	DatabaseInfo *DatabaseInfo `json:"databaseInfo,omitempty"`
}
